### ISSUE TITLE
Nuget?

### ISSUE THREAD

**Issue by binn** [vrchatapi/vrchatapi-csharp#3]
Any NuGet URL or are we to build the library locally?

**Comment by Foorack** [comment]
Thank you for this suggestion! 💖 

`vrchatapi-csharp` has now been uploaded to NuGet as `VRChat.API`. This is still a work-in-progress SDK, bue due to our build system, this project will be automatically updated whenever the API specification is updated. This means there is certain guarantees/probability this package will remain relatively up-to-date with the API itself. Installation and Getting Started instructions should be on the NuGet page.

**https://www.nuget.org/packages/VRChat.API**

Please try use it, and report any bugs or problems you find! 👍
